apiVersion: v1
kind: Service
metadata:
  name: model-compra-comigo
  namespace: model-compra-comigo
spec:
  type: NodePort
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    nodePort: 32100
  selector:
    app: model-compra-comigo
